### ISSUE TITLE
Support for code blocks

### ISSUE THREAD

**Issue by nicocharlery** [nilclass/elixir_org#1]
Hi @nilclass 

First of all, thank you for sharing this awesome library.
I've noticed that code blocks are interpreted as simple comments, and the reference of them get aggregated at the document level without any value.
```
#+BEGIN_SRC sql
...
#+END_SRC
```

What would be useful is to have the flag within a Paragraph, so we can reconstruct an org file with code blocks  to another format (eg. html).

Cheers!

**Comment by nilclass** [comment]
@bokay Thanks for the suggestion. I have added a simple implementation for extracting code blocks.
Code blocks are `Org.Content` objects, with a `lang` attribute and raw `lines` of code.
Limitations are:
- `switches` and `header-arguments` are not parsed, but the raw source is available as `details`
- `#+NAME: <name>` is not extracted

**Comment by nicocharlery** [comment]
@nilclass Thank you very much for this feature! 💛

**Comment by nicocharlery** [comment]
Works like a charm 👍🏾!! Thank you again :)
